### PR TITLE
emscripten-support - Work on a running Emscripten build

### PR DESCRIPTION
**Pull request by raffclar**

### CODE REVIEW

**Comment by bwrsandman** [comment]
Could you add the commandline you use to configure with emscripten to the description

**Comment by bwrsandman** [comment]
Getting this build error
```
In file included from openblack/external/imgui/imgui.cpp:770:
In file included from openblack/external/imgui/imgui.h:2244:
In file included from openblack/external/imgui/imgui_user.h:1:
In file included from $HOME/.emscripten_cache/sysroot/include/c++/v1/string:504:
In file included from $HOME/.emscripten_cache/sysroot/include/c++/v1/string_view:175:
In file included from $HOME/.emscripten_cache/sysroot/include/c++/v1/__string:57:
In file included from $HOME/.emscripten_cache/sysroot/include/c++/v1/algorithm:643:
In file included from $HOME/.emscripten_cache/sysroot/include/c++/v1/memory:653:
$HOME/.emscripten_cache/sysroot/include/c++/v1/typeinfo:221:16: error: reinterpret_cast from 'std::__type_info_implementations::__non_unique_arm_rtti_bit_impl::__type_name_t' (aka 'unsigned int') to 'size_t' (aka 'unsigned long') is not allowed
        return reinterpret_cast<size_t>(__v);
```

**Comment by raffclar** [comment]
Will take a look later today

**Comment by raffclar** [comment]
> 
> 
> Getting this build error among many other c++ standard library errors. Think my emscripten version is bad (2.0.13)
> 
> ```
> In file included from openblack/external/imgui/imgui.cpp:770:
> In file included from openblack/external/imgui/imgui.h:2244:
> In file included from openblack/external/imgui/imgui_user.h:1:
> In file included from $HOME/.emscripten_cache/sysroot/include/c++/v1/string:504:
> In file included from $HOME/.emscripten_cache/sysroot/include/c++/v1/string_view:175:
> In file included from $HOME/.emscripten_cache/sysroot/include/c++/v1/__string:57:
> In file included from $HOME/.emscripten_cache/sysroot/include/c++/v1/algorithm:643:
> In file included from $HOME/.emscripten_cache/sysroot/include/c++/v1/memory:653:
> $HOME/.emscripten_cache/sysroot/include/c++/v1/typeinfo:221:16: error: reinterpret_cast from 'std::__type_info_implementations::__non_unique_arm_rtti_bit_impl::__type_name_t' (aka 'unsigned int') to 'size_t' (aka 'unsigned long') is not allowed
>         return reinterpret_cast<size_t>(__v);
> ```

I'm using:
https://github.com/emscripten-core/emsdk.git @ 6357c6dcab65ebdda86c5a75945c508b3038cb59
cmake 3.17.0

Libraries using vcpkg:
```
cxxopts:wasm32-emscripten                          2.2.1            This is a lightweight C++ option parser library,...
entt:wasm32-emscripten                             3.6.0            Gaming meets modern C++ - a fast and reliable en...
fmt:wasm32-emscripten                              7.1.3            Formatting library for C++. It can be used as a ...
glm:wasm32-emscripten                              0.9.9.8          OpenGL Mathematics (GLM)
sdl2:wasm32-emscripten                             2.0.14#3         Simple DirectMedia Layer is a cross-platform dev...
spdlog:wasm32-emscripten                           1.8.0#2          Very fast, header only, C++ logging library
```

Commands
```
mkdir -p embuild && cd embuild
emcmake cmake ../ -DEMSCRIPTEN=1 -DCMAKE_TOOLCHAIN_FILE=/home/xo/vcpkg/scripts/buildsystems/vcpkg.cmake
make
cp ../index.html bin/
cd bin
emrun index.html --serve_after_close
```

**Comment by bwrsandman** [comment]
How do you install the `wasm32-emscripten` triplets?

**Pull request closed without merging**
