### PR TITLE
Fix std::vector out-of-bounds access when constructing std::span objects

### PR DESCRIPTION
**Pull request by raffclar**

### CODE REVIEW

**Comment by raffclar** [comment]
Working locally with msvc. No out-of-bounds / access violations with this.

**Comment by raffclar** [comment]
@bwrsandman Can you check when you have a sec

**Review by bwrsandman — APPROVED** [review]
Looks fine. I assume you've tested

**Comment by raffclar** [comment]
> Looks fine. I assume you've tested

Windows only. Don't see how it could fail now though

**Pull request merged**
