### PR TITLE
Rename l3d_file.h/cpp to L3DFile.h/cpp

### PR DESCRIPTION
**Pull request by raffclar**

### CODE REVIEW

**Comment by bwrsandman** [comment]
Can we hold off on the renaming after my other PR is done? I don't want to deal with merge conflicts.

**Comment by bwrsandman** [comment]
There's also the naming of l3d_tool, g3d and lnd

**Comment by handsomematt** [comment]
tool naming is fine like that, just public header files to be consistent with everything else

**Comment by bwrsandman** [comment]
Remember to treat l3d, g3d and lnd kind of like a third party for the includes and as a concept.

**Comment by raffclar** [comment]
Still hold off?

**Comment by bwrsandman** [comment]
yes

**Comment by bwrsandman** [comment]
Feel free to do the rename now

**Pull request merged**
