### PR TITLE
Warnings

### PR DESCRIPTION
**Pull request by bwrsandman**
Fix most warnings on clang on linux.
Enable warnings on msvc.

### CODE REVIEW

**Comment by bwrsandman** [comment]
Because gcc and clang produce different errors for unused parameters and have different whitelisting flags.
I didn't want to put different options for different compilers (except for msvc).
We can add it later though.
As for not doing unused-xyz warnings: It makes a lot of sense for a reverse engineered game to have unused variables during early stages.

**Comment by bwrsandman** [comment]
I also didn't add `/WX` on Windows because I'm on Linux.

**Comment by janisozaur** [comment]
Unknown `-Wno-*` options are silently ignored, at least until you hit other error, then they get displayed as well. You could provide all required forms and enable `-Werror`

**Comment by bwrsandman** [comment]
They were not silently ignored when I tried them earlier. Maybe I made a typo.

**Comment by janisozaur** [comment]
Maybe you hit the other case: there was an error caused by enabling another option, then unrecognized flags would get reported as error as well.

https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

> no diagnostic is produced for `-Wno-unknown-warning` unless other diagnostics are being produced. This allows the use of new `-Wno-` options with old compilers, but if something goes wrong, the compiler warns that an unrecognized option is present.

**Comment by bwrsandman** [comment]
That's probably it

**Pull request merged**
