### PR TITLE
bgfx: Move back to upstream bgfx

### PR DESCRIPTION
**Pull request by bwrsandman**
Our use of bgfx https://github.com/openblack/bgfx has a few modifications
- [x] Fixes to shaderc and shader loading for our terrain fragment shader https://github.com/bkaradzic/bgfx/pull/1920
- [x] Fixes to instance rebinds for our submesh primitive rendering:
    - [x] https://github.com/bkaradzic/bgfx/pull/1919
    - [x] https://github.com/bkaradzic/bgfx/pull/2020
- [x] Data made available for profiler, mainly view `gpuTimeBegin`, `gpuTimeEnd`,  `cpuTimeBegin`, `cpuTimeEnd` (https://github.com/bkaradzic/bgfx/pull/1921)
- [x] The sky texture has color order inverted in OpenGL but not in D3D (https://github.com/bkaradzic/bgfx/pull/1932)
- [x] The L3D RGBA4 textures have inverted color order in some backends (https://github.com/bkaradzic/bgfx/pull/2029)

Once these changes are merged, we can switch from using our own fork to using upstream.

### CODE REVIEW

**Comment by bwrsandman** [comment]
There might be a slight difference to merge upstream:
https://github.com/openblack/bgfx/commit/1cfffa6a42d743728957338e197e41d8e5e698f3
https://github.com/bkaradzic/bgfx/pull/1919/commits/1157e78631069b1778bf06f50591ad905c950e5a

**Comment by handsomematt** [comment]
would rather we stayed on a fork, lets us develop / change bgfx when we need to

**Comment by bwrsandman** [comment]
I still like this issue up to keep track of our patches and to be able to test upstream

**Comment by handsomematt** [comment]
Sticking to our bgfx.cmake fork so closing issue. Any differing upstream changes should go on that repo, but for the most part any bgfx changes should get upstreamed quickly.

**Pull request closed without merging**
