### PR TITLE
Implement drawing of multiple submeshes using a Model component

### PR DESCRIPTION
**Pull request by raffclar**

### CODE REVIEW

**Comment by raffclar** [comment]
I'm not particularly keen on this solution. I'm thinking something like `std::map<submeshType, int>` where 
```C++
enum class submeshType
{
    day,
    night,
    physics,
    lod
}
```

or we have three to four arrays of static size 10 like this:

```C++
struct ModelComponent
{
   int day[10],
   int night[10],
   int physics[10],
   int lod[10]
   ...
   MeshId mesh;
}
```

@handsomematt Thoughts?

**Comment by handsomematt** [comment]
I would honestly much rather not have a Model component, instead in the renderer pull from Abode components, etc.. and then have the renderer manage it all. I think that would grant us more flexability.

**Comment by raffclar** [comment]
I'm leaning towards that now. Do we now need a new enum of all the various building, animal, etc types? We don't want to rely on the MeshId for specifying which building type to render or do we?

**Comment by handsomematt** [comment]
Yeah, we would've needed that enum regardless for logical work too, so it's not all bad. Here are some enums the game uses:

```c
//*****************************************************************************
// ENUM Values: ABODE_NUMBER
//*****************************************************************************
enum     ABODE_NUMBER
{
    ABODE_NUMBER_INVALID                            = -1 ,
    ABODE_NUMBER_A                                  =  0 ,
    ABODE_NUMBER_B                                  =  1 ,
    ABODE_NUMBER_C                                  =  2 ,
    ABODE_NUMBER_D                                  =  3 ,
    ABODE_NUMBER_E                                  =  4 ,
    ABODE_NUMBER_F                                  =  5 ,
    ABODE_NUMBER_TOTEM                              =  6 ,
    ABODE_NUMBER_STORAGE_PIT                        =  7 ,
    ABODE_NUMBER_CRECHE                             =  8 ,
    ABODE_NUMBER_WORKSHOP                           =  9 ,
    ABODE_NUMBER_WONDER                             =  10 ,
    ABODE_NUMBER_GRAVEYARD                          =  11 ,
    ABODE_NUMBER_TOWN_CENTRE                        =  12 ,
    ABODE_NUMBER_FOOTBALL_PITCH                     =  13 ,
    ABODE_NUMBER_SPELL_DISPENSER                    =  14 ,
    ABODE_NUMBER_FIELD                              =  15 ,
    ABODE_NUMBER_LAST                               =  16 ,
};
//*****************************************************************************
// ENUM Values: ABODE_INFO
//*****************************************************************************
enum     ABODE_INFO
{
    ABODE_INFO_NONE                                 = -1 ,
    ABODE_INFO_CELTIC_HUT                           =  0 ,
    ABODE_INFO_CELTIC_TENT                          =  1 ,
    ABODE_INFO_CELTIC_SHACK_X                       =  2 ,
    ABODE_INFO_CELTIC_SHACK_Y                       =  3 ,
    ABODE_INFO_CELTIC_TEMPLE_X                      =  4 ,
    ABODE_INFO_CELTIC_TEMPLE_Y                      =  5 ,
    ABODE_INFO_CELTIC_TOTEM                         =  6 ,
    ABODE_INFO_CELTIC_STORAGE_PIT                   =  7 ,
    ABODE_INFO_CELTIC_CRECHE                        =  8 ,
    ABODE_INFO_CELTIC_WORKSHOP                      =  9 ,
    ABODE_INFO_CELTIC_WONDER                        =  10 ,
    ABODE_INFO_CELTIC_GRAVEYARD                     =  11 ,
    ABODE_INFO_CELTIC_TOWN_CENTRE                   =  12 ,
    ABODE_INFO_CELTIC_FOOTBALL_PITCH                =  13 ,
    ABODE_INFO_CELTIC_SPELL_DISPENSER               =  14 ,
    ABODE_INFO_CELTIC_FIELD                         =  15 ,
    ABODE_INFO_AFRICAN_HUT                          =  16 ,
    ABODE_INFO_AFRICAN_TENT                         =  17 ,
    ABODE_INFO_AFRICAN_SHACK_X                      =  18 ,
    ABODE_INFO_AFRICAN_SHACK_Y                      =  19 ,
    ABODE_INFO_AFRICAN_TEMPLE_X                     =  20 ,
    ABODE_INFO_AFRICAN_TEMPLE_Y                     =  21 ,
    ABODE_INFO_AFRICAN_TOTEM                        =  22 ,
    ABODE_INFO_AFRICAN_STORAGE_PIT                  =  23 ,
    ABODE_INFO_AFRICAN_CRECHE                       =  24 ,
    ABODE_INFO_AFRICAN_WORKSHOP                     =  25 ,
    ABODE_INFO_AFRICAN_WONDER                       =  26 ,
    ABODE_INFO_AFRICAN_GRAVEYARD                    =  27 ,
    ABODE_INFO_AFRICAN_TOWN_CENTRE                  =  28 ,
    ABODE_INFO_AFRICAN_FOOTBALL_PITCH               =  29 ,
    ABODE_INFO_AFRICAN_SPELL_DISPENSER              =  30 ,
    ABODE_INFO_AFRICAN_FIELD                        =  31 ,
    ABODE_INFO_AZTEC_HUT                            =  32 ,
    ABODE_INFO_AZTEC_TENT                           =  33 ,
    ABODE_INFO_AZTEC_SHACK_X                        =  34 ,
    ABODE_INFO_AZTEC_SHACK_Y                        =  35 ,
    ABODE_INFO_AZTEC_TEMPLE_X                       =  36 ,
    ABODE_INFO_AZTEC_TEMPLE_Y                       =  37 ,
    ABODE_INFO_AZTEC_TOTEM                          =  38 ,
    ABODE_INFO_AZTEC_STORAGE_PIT                    =  39 ,
    ABODE_INFO_AZTEC_CRECHE                         =  40 ,
    ABODE_INFO_AZTEC_WORKSHOP                       =  41 ,
    ABODE_INFO_AZTEC_WONDER                         =  42 ,
    ABODE_INFO_AZTEC_GRAVEYARD                      =  43 ,
    ABODE_INFO_AZTEC_TOWN_CENTRE                    =  44 ,
    ABODE_INFO_AZTEC_FOOTBALL_PITCH                 =  45 ,
    ABODE_INFO_AZTEC_SPELL_DISPENSER                =  46 ,
    ABODE_INFO_AZTEC_FIELD                          =  47 ,
    ABODE_INFO_JAPANESE_HUT                         =  48 ,
    ABODE_INFO_JAPANESE_TENT                        =  49 ,
    ABODE_INFO_JAPANESE_SHACK_X                     =  50 ,
    ABODE_INFO_JAPANESE_SHACK_Y                     =  51 ,
    ABODE_INFO_JAPANESE_TEMPLE_X                    =  52 ,
    ABODE_INFO_JAPANESE_TEMPLE_Y                    =  53 ,
    ABODE_INFO_JAPANESE_TOTEM                       =  54 ,
    ABODE_INFO_JAPANESE_STORAGE_PIT                 =  55 ,
    ABODE_INFO_JAPANESE_CRECHE                      =  56 ,
    ABODE_INFO_JAPANESE_WORKSHOP                    =  57 ,
    ABODE_INFO_JAPANESE_WONDER                      =  58 ,
    ABODE_INFO_JAPANESE_GRAVEYARD                   =  59 ,
    ABODE_INFO_JAPANESE_TOWN_CENTRE                 =  60 ,
    ABODE_INFO_JAPANESE_FOOTBALL_PITCH              =  61 ,
    ABODE_INFO_JAPANESE_SPELL_DISPENSER             =  62 ,
    ABODE_INFO_JAPANESE_FIELD                       =  63 ,
    ABODE_INFO_INDIAN_HUT                           =  64 ,
    ABODE_INFO_INDIAN_TENT                          =  65 ,
    ABODE_INFO_INDIAN_SHACK_X                       =  66 ,
    ABODE_INFO_INDIAN_SHACK_Y                       =  67 ,
    ABODE_INFO_INDIAN_TEMPLE_X                      =  68 ,
    ABODE_INFO_INDIAN_TEMPLE_Y                      =  69 ,
    ABODE_INFO_INDIAN_TOTEM                         =  70 ,
    ABODE_INFO_INDIAN_STORAGE_PIT                   =  71 ,
    ABODE_INFO_INDIAN_CRECHE                        =  72 ,
    ABODE_INFO_INDIAN_WORKSHOP                      =  73 ,
    ABODE_INFO_INDIAN_WONDER                        =  74 ,
    ABODE_INFO_INDIAN_GRAVEYARD                     =  75 ,
    ABODE_INFO_INDIAN_TOWN_CENTRE                   =  76 ,
    ABODE_INFO_INDIAN_FOOTBALL_PITCH                =  77 ,
    ABODE_INFO_INDIAN_SPELL_DISPENSER               =  78 ,
    ABODE_INFO_INDIAN_FIELD                         =  79 ,
    ABODE_INFO_EGYPTIAN_HUT                         =  80 ,
    ABODE_INFO_EGYPTIAN_TENT                        =  81 ,
    ABODE_INFO_EGYPTIAN_SHACK_X                     =  82 ,
    ABODE_INFO_EGYPTIAN_SHACK_Y                     =  83 ,
    ABODE_INFO_EGYPTIAN_TEMPLE_X                    =  84 ,
    ABODE_INFO_EGYPTIAN_TEMPLE_Y                    =  85 ,
    ABODE_INFO_EGYPTIAN_TOTEM                       =  86 ,
    ABODE_INFO_EGYPTIAN_STORAGE_PIT                 =  87 ,
    ABODE_INFO_EGYPTIAN_CRECHE                      =  88 ,
    ABODE_INFO_EGYPTIAN_WORKSHOP                    =  89 ,
    ABODE_INFO_EGYPTIAN_WONDER                      =  90 ,
    ABODE_INFO_EGYPTIAN_GRAVEYARD                   =  91 ,
    ABODE_INFO_EGYPTIAN_TOWN_CENTRE                 =  92 ,
    ABODE_INFO_EGYPTIAN_FOOTBALL_PITCH              =  93 ,
    ABODE_INFO_EGYPTIAN_SPELL_DISPENSER             =  94 ,
    ABODE_INFO_EGYPTIAN_FIELD                       =  95 ,
    ABODE_INFO_GREEK_HUT                            =  96 ,
    ABODE_INFO_GREEK_TENT                           =  97 ,
    ABODE_INFO_GREEK_SHACK_X                        =  98 ,
    ABODE_INFO_GREEK_SHACK_Y                        =  99 ,
    ABODE_INFO_GREEK_TEMPLE_X                       =  100 ,
    ABODE_INFO_GREEK_TEMPLE_Y                       =  101 ,
    ABODE_INFO_GREEK_TOTEM                          =  102 ,
    ABODE_INFO_GREEK_STORAGE_PIT                    =  103 ,
    ABODE_INFO_GREEK_CRECHE                         =  104 ,
    ABODE_INFO_GREEK_WORKSHOP                       =  105 ,
    ABODE_INFO_GREEK_WONDER                         =  106 ,
    ABODE_INFO_GREEK_GRAVEYARD                      =  107 ,
    ABODE_INFO_GREEK_TOWN_CENTRE                    =  108 ,
    ABODE_INFO_GREEK_FOOTBALL_PITCH                 =  109 ,
    ABODE_INFO_GREEK_SPELL_DISPENSER                =  110 ,
    ABODE_INFO_GREEK_FIELD                          =  111 ,
    ABODE_INFO_NORSE_HUT                            =  112 ,
    ABODE_INFO_NORSE_TENT                           =  113 ,
    ABODE_INFO_NORSE_SHACK_X                        =  114 ,
    ABODE_INFO_NORSE_SHACK_Y                        =  115 ,
    ABODE_INFO_NORSE_TEMPLE_X                       =  116 ,
    ABODE_INFO_NORSE_TEMPLE_Y                       =  117 ,
    ABODE_INFO_NORSE_TOTEM                          =  118 ,
    ABODE_INFO_NORSE_STORAGE_PIT                    =  119 ,
    ABODE_INFO_NORSE_CRECHE                         =  120 ,
    ABODE_INFO_NORSE_WORKSHOP                       =  121 ,
    ABODE_INFO_NORSE_WONDER                         =  122 ,
    ABODE_INFO_NORSE_GRAVEYARD                      =  123 ,
    ABODE_INFO_NORSE_TOWN_CENTRE                    =  124 ,
    ABODE_INFO_NORSE_FOOTBALL_PITCH                 =  125 ,
    ABODE_INFO_NORSE_SPELL_DISPENSER                =  126 ,
    ABODE_INFO_NORSE_FIELD                          =  127 ,
    ABODE_INFO_TIBETAN_HUT                          =  128 ,
    ABODE_INFO_TIBETAN_TENT                         =  129 ,
    ABODE_INFO_TIBETAN_SHACK_X                      =  130 ,
    ABODE_INFO_TIBETAN_SHACK_Y                      =  131 ,
    ABODE_INFO_TIBETAN_TEMPLE_X                     =  132 ,
    ABODE_INFO_TIBETAN_TEMPLE_Y                     =  133 ,
    ABODE_INFO_TIBETAN_TOTEM                        =  134 ,
    ABODE_INFO_TIBETAN_STORAGE_PIT                  =  135 ,
    ABODE_INFO_TIBETAN_CRECHE                       =  136 ,
    ABODE_INFO_TIBETAN_WORKSHOP                     =  137 ,
    ABODE_INFO_TIBETAN_WONDER                       =  138 ,
    ABODE_INFO_TIBETAN_GRAVEYARD                    =  139 ,
    ABODE_INFO_TIBETAN_TOWN_CENTRE                  =  140 ,
    ABODE_INFO_TIBETAN_FOOTBALL_PITCH               =  141 ,
    ABODE_INFO_TIBETAN_SPELL_DISPENSER              =  142 ,
    ABODE_INFO_TIBETAN_FIELD                        =  143 ,
    ABODE_INFO_ARK_DRY_DOCK                         =  144 ,
    ABODE_INFO_ARK_WRECK                            =  145 ,
    ABODE_INFO_BELLTOWER                            =  146 ,
    ABODE_INFO_LAST                                 =  147 ,
};

//*****************************************************************************
// ENUM Values: VILLAGER_NUMBER
//*****************************************************************************
enum     VILLAGER_NUMBER
{
    VILLAGER_NUMBER_HOUSEWIFE                       =  0 ,
    VILLAGER_NUMBER_FORESTER                        =  1 ,
    VILLAGER_NUMBER_FISHERMAN                       =  2 ,
    VILLAGER_NUMBER_FARMER                          =  3 ,
    VILLAGER_NUMBER_SHEPHERD                        =  4 ,
    VILLAGER_NUMBER_LEADER                          =  5 ,
    VILLAGER_NUMBER_TRADER                          =  6 ,
    VILLAGER_NUMBER_LAST                            =  7 ,
};
```

Obviously we don't have to match these, but gives a good idea of how they handle it. These enums are used throughout the scripts and also further in the LHVM, so it might be a good idea to match them up integer wise. (Especially for LHVM where they use constant values.)

**Comment by raffclar** [comment]
How did you get those enums? Also do we have enums for trees, rocks, toys (dice, ball)? There are over 600 meshes - scared I'll have to write a lot of enum entries.

**Comment by handsomematt** [comment]
> 
> 
> How did you get those enums? Also do we have enums for trees, rocks, toys (dice, ball)? There are over 600 meshes - scared I'll have to write a lot of enum entries.

I have sent them over Discord, you can probably script to generate better enums.

**Pull request merged**
