### PR TITLE
Use stringviews to share strings between Lexer and Tokens

### PR DESCRIPTION
**Pull request by captnfab**
Based on https://github.com/openblack/openblack/pull/391 but uses stringviews to share strings between Lexer and Tokens.

### CODE REVIEW

**Comment by captnfab** [comment]
And there's this issue on macOs, I don't know why it doesn't know the constructor `std::string_view(iterator_start, iterator_end)`…

**Comment by bwrsandman** [comment]
According to the build, it's AppleClang 13.0.0.13000029 from XCode 13.2.1

**Comment by bwrsandman** [comment]
I feel like I had a similar issue with spans here https://github.com/openblack/openblack/pull/336

**Comment by bwrsandman** [comment]
Maybe this constructor will work
```c++
constexpr basic_string_view( const CharT* s, size_type count );
```

**Comment by bwrsandman** [comment]
Or we can try setting clang 13.0.1 with `$(brew --prefix llvm)/bin/clang`

**Comment by handsomematt** [comment]
Does this actually work? The Lexer is scoped to Script::load, making it a string_view keeps the ownership on the Lexer which would get deleted?

**Comment by captnfab** [comment]
@bwrsandman: yeah, correct. Given how the tokens are used now, they cannot outlive the Lexer, so it's fine. I agree with you about `source_` not being const.

I also agree about the fact that this would bring only little improvement. It was just a pretense to study the lexer and play with stringviews. So if you don't see this being merged, I don't mind closing the PR.

**Comment by bwrsandman** [comment]
You can close it

**Pull request closed without merging**
