### PR TITLE
Update contribution guidelines

### PR DESCRIPTION
**Pull request by bwrsandman**

### CODE REVIEW

**Review by handsomematt — APPROVED** [review]
Everything makes sense, do we need extensive style guidelines when clang-format does everything? Worried the length of this will turn some people off from contributing more than it's meant to encourage

**Comment by bwrsandman** [comment]
@Sofistico Do these guidelines encourage or discourage you from contributing?

https://github.com/openblack/openblack/blob/f9e7b63e3fb8b104aeef99b066b2a5d35d6eca7c/.github/contributing.md

**Comment by Sofistico** [comment]
Encourage!
At the very least it gives me where to look if i have any doubt and don't want to ask away at the discord or here

**Comment by Sofistico** [comment]
And in regards to the style guidelines, makes it so that you know exactly what you did wrong that clang might be annoyed about

**Pull request merged**
