### PR TITLE
Game: Add game logic loop

### PR DESCRIPTION
**Pull request by bwrsandman**
PR depends on other PRs before being merged:
- [x] UI refactoring #257 

Game normally updates entities at 10Hz.
Fast forward doubles the rate and slow mo halves it.
Add option in menu to set duration multiplier.

### CODE REVIEW

**Comment by bwrsandman** [comment]
Open conversation: I think it's a good idea to be thinking about updating the entities on a game update loop that can more precisely run at the desired rate.
This requires making some adjustments for thread safety (mutex, atomics or double buffering entities).

**Comment by raffclar** [comment]
Reviewing this in a sec

**Review by raffclar — CHANGES_REQUESTED** [review]
sent you a patch

**Comment by bwrsandman** [comment]
> sent you a patch

I don't see it

**Comment by raffclar** [comment]
> 
> 
> > sent you a patch
> 
> I don't see it

https://gist.github.com/raffclar/d83498741875511a1f03147328b2dd99

**Review by raffclar — APPROVED** [review]

**Pull request merged**
