### PR TITLE
hunter: manually provide EnTT and use it

### PR DESCRIPTION
**Pull request by NeroBurner**
EnTT is a good cmake project with no dependencies, easy to download with hunter

### CODE REVIEW

**Comment by handsomematt** [comment]
Can you remove the submodule for EnTT as well as the `add_subdirectory("${EXTERNAL_DIR}/entt")` line too since this resolves any need for that 👍

**Comment by NeroBurner** [comment]
Ubuntu has no libentt-dev as far as I can see. This would break the Ubuntu builds

**Comment by handsomematt** [comment]
makes sense, not sure what to do about that then 🤔

**Comment by NeroBurner** [comment]
I propose to keep the entt submodule :man_shrugging:

**Pull request merged**
