### PR TITLE
CI travis: fix mingw build

### PR DESCRIPTION
**Pull request by NeroBurner**
mingw.threads everywhere!!!

- main.cpp: lower case windows.h include for mingw
- ci: travis: enable cache for .hunter
- ~~provide mingw-std-threads as submodule~~
- SUBSYSTEM:WINDOWS only for MSVC builds

 ~~don't yet merge, somehow spdlog breaks under Ubuntu 18.04 bionic~~  :thinking:
Edit: Ubuntu 18.04 is broken by old system spdlog. see https://github.com/openblack/openblack/issues/61

### CODE REVIEW

**Comment by NeroBurner** [comment]
nope spdlog on bionic is already broken in master, still probably my fault, but a different PR

**Comment by NeroBurner** [comment]
ready to merge. fixed the mingw build by using fedora 31 image, which provides mingw 9.1.0. All other Ubuntu images (disco, eona, even Debian Sid) provide mingw 8.3.0

**Comment by janisozaur** [comment]
I'm a fedora packager, packaged mingw libraries for OpenLoco in the past. If you need some packages in there, let me know.

**Comment by NeroBurner** [comment]
@janisozaur thx for the offer :) currently I only need mingw-w64-g++ (9.1.0 awesome!), cmake, make and git. The remaining build dependencies are handled by Hunter

**Comment by NeroBurner** [comment]
fixes: https://github.com/openblack/openblack/issues/45

**Pull request merged**
