### PR TITLE
[WIP] Use ninja on appveyor

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
\**sigh*\* why does Windows have to make everything hard?

**Comment by handsomematt** [comment]
Not sure if this works or not?

**Comment by janisozaur** [comment]
Not yet

**Comment by janisozaur** [comment]
It works now.

The benefits it brings:
* Faster builds
  - at least they should be, `msbuild` is ridiculously slow, to the point where _anything_, even invoking compiler manually is faster, but it seems there is still no hunter cache to use, so each job rebuilds dependencies for now as well
* Sane error messages

Before:
```
  LHVMViewer.cpp
C:\projects\openblack\src\LHScriptX\FeatureScriptCommands.cpp(240,24): warning C4244:  '=': conversion from 'double' to 'float', possible loss of data [C:\projects\openblack\_build_vs-16-2019-win64-cxx17_Debug\openblack.vcxproj]
C:\projects\openblack\src\LHVMViewer.cpp(171,54): warning C4267:  'argument': conversion from 'size_t' to 'int', possible loss of data [C:\projects\openblack\_build_vs-16-2019-win64-cxx17_Debug\openblack.vcxproj]
  MeshViewer.cpp
  Renderer.cpp
C:\projects\openblack\src\LHVMViewer.cpp(213,109): warning C4267:  'argument': conversion from 'size_t' to 'int', possible loss of data [C:\projects\openblack\_build_vs-16-2019-win64-cxx17_Debug\openblack.vcxproj]
```
After:
```
[32/50] Building CXX object CMakeFiles\openblack.dir\src\LHVMViewer.cpp.obj
..\src\LHVMViewer.cpp(171): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
..\src\LHVMViewer.cpp(213): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
```

**Comment by janisozaur** [comment]
From [2 minutes 50 seconds, 3 minutes 10 seconds] range to [2 minutes 8 seconds, 2 minutes 18 seconds] range

**Pull request merged**
